# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xwt/Development/Stone

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xwt/Development/Stone

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xwt/Development/Stone/CMakeFiles /home/xwt/Development/Stone/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xwt/Development/Stone/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stone

# Build rule for target.
stone: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stone
.PHONY : stone

# fast build rule for target.
stone/fast:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/build
.PHONY : stone/fast

Channel/TcpChannel.o: Channel/TcpChannel.cpp.o
.PHONY : Channel/TcpChannel.o

# target to build an object file
Channel/TcpChannel.cpp.o:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Channel/TcpChannel.cpp.o
.PHONY : Channel/TcpChannel.cpp.o

Channel/TcpChannel.i: Channel/TcpChannel.cpp.i
.PHONY : Channel/TcpChannel.i

# target to preprocess a source file
Channel/TcpChannel.cpp.i:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Channel/TcpChannel.cpp.i
.PHONY : Channel/TcpChannel.cpp.i

Channel/TcpChannel.s: Channel/TcpChannel.cpp.s
.PHONY : Channel/TcpChannel.s

# target to generate assembly for a file
Channel/TcpChannel.cpp.s:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Channel/TcpChannel.cpp.s
.PHONY : Channel/TcpChannel.cpp.s

Channel/TcpConnection.o: Channel/TcpConnection.cpp.o
.PHONY : Channel/TcpConnection.o

# target to build an object file
Channel/TcpConnection.cpp.o:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Channel/TcpConnection.cpp.o
.PHONY : Channel/TcpConnection.cpp.o

Channel/TcpConnection.i: Channel/TcpConnection.cpp.i
.PHONY : Channel/TcpConnection.i

# target to preprocess a source file
Channel/TcpConnection.cpp.i:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Channel/TcpConnection.cpp.i
.PHONY : Channel/TcpConnection.cpp.i

Channel/TcpConnection.s: Channel/TcpConnection.cpp.s
.PHONY : Channel/TcpConnection.s

# target to generate assembly for a file
Channel/TcpConnection.cpp.s:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Channel/TcpConnection.cpp.s
.PHONY : Channel/TcpConnection.cpp.s

Event/EventLoop_LibEvent.o: Event/EventLoop_LibEvent.cpp.o
.PHONY : Event/EventLoop_LibEvent.o

# target to build an object file
Event/EventLoop_LibEvent.cpp.o:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Event/EventLoop_LibEvent.cpp.o
.PHONY : Event/EventLoop_LibEvent.cpp.o

Event/EventLoop_LibEvent.i: Event/EventLoop_LibEvent.cpp.i
.PHONY : Event/EventLoop_LibEvent.i

# target to preprocess a source file
Event/EventLoop_LibEvent.cpp.i:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Event/EventLoop_LibEvent.cpp.i
.PHONY : Event/EventLoop_LibEvent.cpp.i

Event/EventLoop_LibEvent.s: Event/EventLoop_LibEvent.cpp.s
.PHONY : Event/EventLoop_LibEvent.s

# target to generate assembly for a file
Event/EventLoop_LibEvent.cpp.s:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Event/EventLoop_LibEvent.cpp.s
.PHONY : Event/EventLoop_LibEvent.cpp.s

Public/Sockets.o: Public/Sockets.cpp.o
.PHONY : Public/Sockets.o

# target to build an object file
Public/Sockets.cpp.o:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Public/Sockets.cpp.o
.PHONY : Public/Sockets.cpp.o

Public/Sockets.i: Public/Sockets.cpp.i
.PHONY : Public/Sockets.i

# target to preprocess a source file
Public/Sockets.cpp.i:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Public/Sockets.cpp.i
.PHONY : Public/Sockets.cpp.i

Public/Sockets.s: Public/Sockets.cpp.s
.PHONY : Public/Sockets.s

# target to generate assembly for a file
Public/Sockets.cpp.s:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Public/Sockets.cpp.s
.PHONY : Public/Sockets.cpp.s

Public/Times.o: Public/Times.cpp.o
.PHONY : Public/Times.o

# target to build an object file
Public/Times.cpp.o:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Public/Times.cpp.o
.PHONY : Public/Times.cpp.o

Public/Times.i: Public/Times.cpp.i
.PHONY : Public/Times.i

# target to preprocess a source file
Public/Times.cpp.i:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Public/Times.cpp.i
.PHONY : Public/Times.cpp.i

Public/Times.s: Public/Times.cpp.s
.PHONY : Public/Times.s

# target to generate assembly for a file
Public/Times.cpp.s:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Public/Times.cpp.s
.PHONY : Public/Times.cpp.s

Server.o: Server.cpp.o
.PHONY : Server.o

# target to build an object file
Server.cpp.o:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Server.cpp.o
.PHONY : Server.cpp.o

Server.i: Server.cpp.i
.PHONY : Server.i

# target to preprocess a source file
Server.cpp.i:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Server.cpp.i
.PHONY : Server.cpp.i

Server.s: Server.cpp.s
.PHONY : Server.s

# target to generate assembly for a file
Server.cpp.s:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Server.cpp.s
.PHONY : Server.cpp.s

Service/TcpServer.o: Service/TcpServer.cpp.o
.PHONY : Service/TcpServer.o

# target to build an object file
Service/TcpServer.cpp.o:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Service/TcpServer.cpp.o
.PHONY : Service/TcpServer.cpp.o

Service/TcpServer.i: Service/TcpServer.cpp.i
.PHONY : Service/TcpServer.i

# target to preprocess a source file
Service/TcpServer.cpp.i:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Service/TcpServer.cpp.i
.PHONY : Service/TcpServer.cpp.i

Service/TcpServer.s: Service/TcpServer.cpp.s
.PHONY : Service/TcpServer.s

# target to generate assembly for a file
Service/TcpServer.cpp.s:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Service/TcpServer.cpp.s
.PHONY : Service/TcpServer.cpp.s

Thread/LoopThread.o: Thread/LoopThread.cpp.o
.PHONY : Thread/LoopThread.o

# target to build an object file
Thread/LoopThread.cpp.o:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Thread/LoopThread.cpp.o
.PHONY : Thread/LoopThread.cpp.o

Thread/LoopThread.i: Thread/LoopThread.cpp.i
.PHONY : Thread/LoopThread.i

# target to preprocess a source file
Thread/LoopThread.cpp.i:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Thread/LoopThread.cpp.i
.PHONY : Thread/LoopThread.cpp.i

Thread/LoopThread.s: Thread/LoopThread.cpp.s
.PHONY : Thread/LoopThread.s

# target to generate assembly for a file
Thread/LoopThread.cpp.s:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Thread/LoopThread.cpp.s
.PHONY : Thread/LoopThread.cpp.s

Thread/ThreadPool.o: Thread/ThreadPool.cpp.o
.PHONY : Thread/ThreadPool.o

# target to build an object file
Thread/ThreadPool.cpp.o:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Thread/ThreadPool.cpp.o
.PHONY : Thread/ThreadPool.cpp.o

Thread/ThreadPool.i: Thread/ThreadPool.cpp.i
.PHONY : Thread/ThreadPool.i

# target to preprocess a source file
Thread/ThreadPool.cpp.i:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Thread/ThreadPool.cpp.i
.PHONY : Thread/ThreadPool.cpp.i

Thread/ThreadPool.s: Thread/ThreadPool.cpp.s
.PHONY : Thread/ThreadPool.s

# target to generate assembly for a file
Thread/ThreadPool.cpp.s:
	$(MAKE) -f CMakeFiles/stone.dir/build.make CMakeFiles/stone.dir/Thread/ThreadPool.cpp.s
.PHONY : Thread/ThreadPool.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... stone"
	@echo "... Channel/TcpChannel.o"
	@echo "... Channel/TcpChannel.i"
	@echo "... Channel/TcpChannel.s"
	@echo "... Channel/TcpConnection.o"
	@echo "... Channel/TcpConnection.i"
	@echo "... Channel/TcpConnection.s"
	@echo "... Event/EventLoop_LibEvent.o"
	@echo "... Event/EventLoop_LibEvent.i"
	@echo "... Event/EventLoop_LibEvent.s"
	@echo "... Public/Sockets.o"
	@echo "... Public/Sockets.i"
	@echo "... Public/Sockets.s"
	@echo "... Public/Times.o"
	@echo "... Public/Times.i"
	@echo "... Public/Times.s"
	@echo "... Server.o"
	@echo "... Server.i"
	@echo "... Server.s"
	@echo "... Service/TcpServer.o"
	@echo "... Service/TcpServer.i"
	@echo "... Service/TcpServer.s"
	@echo "... Thread/LoopThread.o"
	@echo "... Thread/LoopThread.i"
	@echo "... Thread/LoopThread.s"
	@echo "... Thread/ThreadPool.o"
	@echo "... Thread/ThreadPool.i"
	@echo "... Thread/ThreadPool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

